apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-19T16:45:59.0304959+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 8d68010098e9b13557bec856c82a4a3946acdd4589abae950541d6464b9385ff
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.8.tgz
    version: 0.1.8
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-07-19T16:45:59.0174024+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.8
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 2b1352365961a32c027f16bd4f8d3782774e8745b6405f8188696ed58c290577
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-19T16:45:59.0033837+02:00"
