apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-18T10:39:06.233507+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: c5746a37b9a6bcf4c5f9dee71d4b090e6cfe9e64320d64d7234e0cbb086ab5f2
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.9.tgz
    version: 0.1.9
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-08-18T10:39:06.22269+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.9
    description: A Helm chart for the Skeleton Gatsby Application
    digest: dff02ddaf7597ad106318c16fb08907c39aac31bea2aa7703c7eb1c6ea3e6a7f
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-18T10:39:06.209622+02:00"
