apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-05-30T16:51:19.743410956+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: f562da7744a44b335afdb6e027c3ac9795fa2eb8d8338e4836c11ac5e435a68d
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.6.tgz
    version: 0.1.6
  opencatalogi:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2022-05-30T16:51:19.729740545+02:00"
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 9b47cba7e481de716aed519acfcc837712dba81220dfddb4814c9ed890d68698
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-05-30T16:51:19.713996741+02:00"
