apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-05-30T16:56:07.185534918+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 0f72c855cd9276b06a6eb82f4f5e1367c9eff7629de3c2671c52de6db1300d74
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.7.tgz
    version: 0.1.7
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-05-30T16:56:07.172265167+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.7
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 701b78bb6529934483bc59d96b7d0ac2051605593fb44a83d7a986a90139f243
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-05-30T16:56:07.15928935+02:00"
