apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:50:41.082214148+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: a4c33a8ea7095911c57608e121eb208322da46941865624f7f8f2ab2fab75b33
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.12.tgz
    version: 0.1.12
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-10-05T15:50:41.067514491+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.12
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 6ec744273818842ea880b4bca8b8be743e3236c6862e18ff3696baf78a6b3dfc
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-10-05T15:50:41.053309072+02:00"
