apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-18T11:07:49.616391+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 1132bcdf8bc1ed71fc6fbe2a227d5a63fc4d70a00c0595ae1c846c4dfc26e67f
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.10.tgz
    version: 0.1.10
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-08-18T11:07:49.606769+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.10
    description: A Helm chart for the Skeleton Gatsby Application
    digest: c4a459d888af85a46ba4c701141a7085ca5b6d11bcef36cd75fb2301c77a4c97
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-18T11:07:49.596028+02:00"
