apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-20T09:38:55.784081158+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 8d68010098e9b13557bec856c82a4a3946acdd4589abae950541d6464b9385ff
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.8.tgz
    version: 0.1.8
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-07-20T09:38:55.767323052+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.8
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 75b8a153e096e2b565283d0358672b64cf53e5a8d986a0d51f8a7b2ff7d73f73
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-20T09:38:55.74768013+02:00"
