apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-05-31T14:18:15.6103633+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 0f72c855cd9276b06a6eb82f4f5e1367c9eff7629de3c2671c52de6db1300d74
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.7.tgz
    version: 0.1.7
  opencatalogi:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-05-31T14:18:15.6023632+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.7
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 9bd2b28b8a81cf404c18f5e977e9bc952fb21753c69b91283753d1fb1f479026
    name: opencatalogi
    type: application
    urls:
    - opencatalogi-0.1.0.tgz
    version: 0.1.0
generated: "2022-05-31T14:18:15.59018+02:00"
